// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Steve.DAL.EF;
using System;

namespace Steve.DAL.Migrations
{
    [DbContext(typeof(SteveContext))]
    [Migration("20171214105344_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Steve.DAL.Entities.EmailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyContent");

                    b.Property<string>("EmailAdress");

                    b.Property<string>("FromAdressTitle");

                    b.Property<DateTime?>("SendingTime");

                    b.Property<string>("Subject");

                    b.Property<string>("ToAddress");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Steve.DAL.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EmailId");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Steve.DAL.Entities.UserEntity", b =>
                {
                    b.HasOne("Steve.DAL.Entities.EmailEntity", "Email")
                        .WithMany("Users")
                        .HasForeignKey("EmailId");
                });
#pragma warning restore 612, 618
        }
    }
}
